=== pedroma2000/PEI-Resources/PEI_FP_1/PEI_FP_01_ex2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="Ingredientes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ingredient" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="categories">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Vegetal"/>
                                        <xs:enumeration value="Dairy"/>
                                        <xs:enumeration value="Sauce"/>
                                        <xs:enumeration value="Herb"/>
                                        <xs:enumeration value="Meat"/>
                                        <xs:enumeration value="Pasta"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="calories">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="unit">
                                                <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:enumeration value="grams"/>
                                                  <xs:enumeration value="mililiters"/>
                                                  <xs:enumeration value="unidades"/>
                                                  </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== pedroma2000/PEI-Resources/PEI_FP_1/PEI_FP_01_ex2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Ingredientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="PEI_FP_01_ex2.xsd">

    <ingredient>
        <name>Spinach</name>
        <categories>Vegetal</categories>
        <calories unit="grams">18</calories>
    </ingredient>

    <ingredient>
        <name>Cheese</name>
        <categories>Dairy</categories>
        <calories unit="grams">25</calories>
    </ingredient>

    <ingredient>
        <name>Tomato Sauce</name>
        <categories>Sauce</categories>
        <calories unit="mililiters">40</calories>
    </ingredient>

    <ingredient>
        <name>Oregano</name>
        <categories>Herb</categories>
        <calories unit="grams">45</calories>
    </ingredient>

    <ingredient>
        <name>Chicken</name>
        <categories>Meat</categories>
        <calories unit="grams">32</calories>
    </ingredient>

    <ingredient>
        <name>Onion Sauce</name>
        <categories>Sauce</categories>
        <calories unit="mililiters">55</calories>
    </ingredient>

    <ingredient>
        <name>Pasta</name>
        <categories>Pasta</categories>
        <calories unit="grams">43</calories>
    </ingredient>
</Ingredientes>
