=== pedroma2000/PEI-Resources/PEI_FP_1/PEI_FP_01_ex1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 
    <xs:element name="emails"> 
        <xs:complexType>
            <xs:sequence>
                <xs:element name="email" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="to" type="xs:string"/>
                            <xs:element name="from" type="xs:string"/>
                            <xs:element name="heading" type="xs:string"/>
                            <xs:element name="type">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Personal"/>
                                        <xs:enumeration value="Work"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="body" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== pedroma2000/PEI-Resources/PEI_FP_1/PEI_FP_01_ex1.xml
<?xml version="1.0" encoding="UTF-8"?>
<emails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="PEI_FP_01_ex1.xsd">
    <email>
        <to>Tove@gmail.com</to>
        <from>Jani@gmail.com</from>
        <heading>Reminder</heading>
        <type>Personal</type>
        <body>Donâ€™t forget me this weekend!</body>
    </email>
    
    <email>
        <to>Tove@gmail.com</to>
        <from>Mari@gmail.com</from>
        <heading>Important</heading>
        <type>Work</type>
        <body>Tomorrow the reunion is at 3pm.</body>
    </email>
</emails>
