=== pedroma2000/PEI-Resources/PEI_FP_5/Parte II/resumoIva.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">
    <xs:element name="resumo" type="resumoType" />
    <xs:complexType name="resumoType">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="taxa" type="taxaType"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="taxaType">
        <xs:sequence>
            <xs:element name="valor_iva" type="xs:float"/>
            <xs:element name="total_sem_iva" type="xs:float"/>
            <xs:element name="total_iva" type="xs:float"/>
            <xs:element name="total_com_iva" type="xs:float"/>
        </xs:sequence>
        <xs:attribute name="tipo" type="xs:string"/>
        <xs:attribute name="codigo" type="xs:string"/>
    </xs:complexType>
</xs:schema>

=== pedroma2000/PEI-Resources/PEI_FP_5/Parte II/returnFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<resumo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="resumoIva.xsd">
    <taxa tipo="IVACON" codigo="Nor">
        <valor_iva>21</valor_iva>
        <total_sem_iva>482.59</total_sem_iva>
        <total_iva>101.34</total_iva>
        <total_com_iva>583.93</total_com_iva>
    </taxa>
    <taxa tipo="IVACON" codigo="Nor">
        <valor_iva>21</valor_iva>
        <total_sem_iva>130</total_sem_iva>
        <total_iva>27.3</total_iva>
        <total_com_iva>157.3</total_com_iva>
    </taxa>
    <taxa tipo="IVACON" codigo="Nor">
        <valor_iva>21</valor_iva>
        <total_sem_iva>2.7</total_sem_iva>
        <total_iva>.57</total_iva>
        <total_com_iva>3.27</total_com_iva>
    </taxa>
    <taxa tipo="IVACON" codigo="Nor">
        <valor_iva>21</valor_iva>
        <total_sem_iva>1093.77</total_sem_iva>
        <total_iva>229.69</total_iva>
        <total_com_iva>1323.46</total_com_iva>
    </taxa>
    <taxa tipo="IVACON" codigo="Nor">
        <valor_iva>21</valor_iva>
        <total_sem_iva>482.59</total_sem_iva>
        <total_iva>101.34</total_iva>
        <total_com_iva>583.93</total_com_iva>
    </taxa>
    <taxa tipo="IVACON" codigo="Nor">
        <valor_iva>21</valor_iva>
        <total_sem_iva>130</total_sem_iva>
        <total_iva>27.3</total_iva>
        <total_com_iva>157.3</total_com_iva>
    </taxa>
    <taxa tipo="IVACON" codigo="RED">
        <valor_iva>5</valor_iva>
        <total_sem_iva>2.7</total_sem_iva>
        <total_iva>.14</total_iva>
        <total_com_iva>2.84</total_com_iva>
    </taxa>
</resumo>
